{% set version = "2.0.9" %}

package:
  name: bob.ip.optflow.liu
  version: {{ version }}

source:
  fn: bob.ip.optflow.liu-{{ version }}.zip
  md5: 12feaab2482e75c2c9d5f46d04f05fb2
  url: https://pypi.io/packages/source/b/bob.ip.optflow.liu/bob.ip.optflow.liu-{{ version }}.zip

build:
  entry_points:
    - bob_of_liu.py = bob.ip.optflow.liu.script.flow:main
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.io.base
    - bob.io.image
    - bob.io.video
    - bob.ip.color
    - pkg-config

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.io.base
    - bob.io.image
    - bob.io.video
    - bob.ip.color

test:
  commands:
    - bob_of_liu.py --help
    - nosetests -sv bob.ip.optflow.liu

  imports:
    - bob
    - bob.ip
    - bob.ip.optflow
    - bob.ip.optflow.liu
    - bob.ip.optflow.liu.script

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Python bindings to the optical flow framework by C. Liu

extra:
  recipe-maintainers:
    - 183amir
